#!/usr/bin/env bash
sudo apt-get install -y axel time
echo "Downloading dependencies"
axel http://d3kbcqa49mib13.cloudfront.net/spark-1.6.1-bin-hadoop1.tgz  > sparkdl &
SPARK_DL_PID=$!
wait $SPARK_DL_PID
echo "install nose"
sudo pip install nose
echo "install numpy"
sudo pip install numpy
wait $SPARK_DL_PID || echo "Spark Downloaded"
tar -xf spark-1.6.1-bin-hadoop1.tgz
echo $?