class Package(object):
    PREP_BUDDY = "com.thoughtworks.datacommons.prepbuddy"
    IMPUTATION = PREP_BUDDY + ".imputations"
    CLUSTER = PREP_BUDDY + ".clusterers"
    NORMALIZERS = PREP_BUDDY + ".normalizers"
    CONNECTOR = PREP_BUDDY + ".python.connector"
    APIJAVA = PREP_BUDDY + ".api.java"
    SMOOTHERS = PREP_BUDDY + ".smoothers"
    TRANSFORMERS = PREP_BUDDY + ".transformers"
    UTILS = PREP_BUDDY + ".utils"
    PYTHON_CONNECTOR = "org.apache.spark.api.python"
