class Package(object):
    PREP_BUDDY = "org.apache.datacommons.prepbuddy"
    IMPUTATION = PREP_BUDDY + ".cleansers.imputation"
    DEDUPE = PREP_BUDDY + ".cleansers.dedupe"
    CLUSTER = PREP_BUDDY + ".cluster"
    NORMALIZERS = PREP_BUDDY + ".normalizers"
    CONNECTOR = PREP_BUDDY + ".python.connector"
    APIJAVA = PREP_BUDDY + ".api.java"
    APIJAVATYPES = APIJAVA + ".types"
    SMOOTHERS = PREP_BUDDY + ".smoothers"
    TRANSFORMERS = PREP_BUDDY + ".transformers"
    UTILS = PREP_BUDDY + ".utils"
    PYTHON_CONNECTOR = "org.apache.spark.api.python"
